# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: ls
- script: dotnet build ./Web/SwingDataViewer/SwingDataViewer.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
